name: Setup MSBuild, NuGet and Build Application Solution
inputs:
  sln-name:
    required: true
  configuration:
    required: true
runs:
  using: composite
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4

    - name: Restore NuGet packages
      run: nuget restore ${{inputs.sln-name}}
      shell: pwsh
    - name: Build Solution: ${{inputs.sln-name}}
      run: msbuild ${{inputs.sln-name}} /p:Configuration=${{inputs.configuration}}
      shell: pwsh
