name: Core Application Security SAST/SCA Scan
description: Runs Fortify FoD setup plus SAST and SCA scans
inputs:
  fod-url:
    description: "FOD URL"
    required: True
  release-name:
    description: "Release Name"
    required: true
  sdlc-status:
    description: "SDLC Status"
    required: true
  application-type:
    description: "Application Type"
    required: true
  application-criticality:
    description: "Application criticality"
    required: true
  entitlement-frequency:
    description: "entitlement frequency"
    required: True
  entitlement-id:
    description: "entitlement ID"
    required: true
  package-extra-opts:
    required: false
    type: string
    default: ''
runs:
  using: composite
  steps:
    - uses: fortify/github-action@v3
      with:
        sast-scan: true
        debricked-sca-scan: true
      env:
        FOD_URL: ${{ inputs.fod-url }}
        FOD_CLIENT_ID: ${{ env.FOD_CLIENT_ID }}
        FOD_CLIENT_SECRET: ${{ env.FOD_CLIENT_SECRET }}
        FOD_LOGIN_EXTRA_OPTS: --socket-timeout=60s
        DO_SETUP: true
        DO_WAIT: true
        DO_POLICY_CHECK: true
        FOD_RELEASE: ${{ github.event.repository.name }}:${{ inputs.release-name }}
        SETUP_EXTRA_OPTS: |
          --oss
          --sdlc-status="${{ inputs.sdlc-status }}"
          --app-type="${{ inputs.application-type }}"
          --app-criticality="${{ inputs.application-criticality }}"
          --app-description="${{ github.server_url }}/${{ github.repository }}"
        SAST_ASSESSMENT_TYPE: "Static Assessment"
        FOD_SAST_SCAN_EXTRA_OPTS: |
          --oss
          --entitlement-frequency="${{ inputs.entitlement-frequency }}"
          --entitlement-id=${{ inputs.entitlement-id }}
          --notes="${{ github.sha }}"
        DO_SCA_SCAN: true
        PACKAGE_EXTRA_OPTS: |
          -exclude="**/tests/**"
          -exclude="**/node_modules/**"
          -exclude="**/.venv/**"
          -exclude="**/.pyenv/**"
          -exclude="**/venv/**"
          -exclude="**/__pycache__/**"
          -exclude="**/.pytest_cache/**"
          -exclude="**/.mypy_cache/**"
          -exclude="**/.eggs/**"
          -exclude="**/*.egg-info/**"
          -exclude="**/vendor/**"
          -exclude="**/var/cache/**"
          -exclude="**/var/log/**"
          -exclude="**/.phpunit.result.cache"
          -exclude="**/TestResults/**"
          ${{ inputs.package-extra-opts }}
        
