name: Setup Node JS
description: Setup Node JS
inputs:
  node-version:
    required: true
    type: string
  shell:
    required: true
    type: string
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v7
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
    - name: Install dependencies
      run: npm install
      shell: ${{ inputs.shell }}
    - name: Build project
      run: npm run build
      shell: ${{ inputs.shell }}
