name: OpenText Core Application Security Scan
on:
  workflow_call:
    inputs:
      sdlc-status:
        required: false
        type: string
        default: "Development"
      assessment-type:
        required: false
        type: string
        default: "Static Assessment"
      entitlement-frequency:
        required: false
        type: string
        default: "Subscription"
      app-type:
        required: false
        type: string
        default: "Web"
      app-criticality:
        required: false
        type: string
        default: Medium
jobs:
  fortify:
    runs-on: ubuntu-latest
    permissions: # When overriding default permissions, following are required
      contents: read
      security-events: write
      pull-requests: write     # Required if DO_PR_COMMENT is set to true
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Setup Poetry
        uses: snok/install-poetry@v1
      # Run Fortify Scan
      - name: Run Fortify Scan
        uses: fortify/github-action@v3
        with:
          sast-scan: true
          # debricked-sca-scan: true # For FoD, run an open-source scan as part of the SAST scan (ignored if SAST scan is disabled).
        env:
          FOD_URL: ${{ vars.FOD_URL }}  # Must be Through GitHub variable, not secret
          # Either tenant/user/password or client id/secret are required
          FOD_CLIENT_ID: ${{ secrets.FOD_CLIENT_ID }} # API KEY
          FOD_CLIENT_SECRET: ${{ secrets.FOD_CLIENT_SECRET }} # SECRET KEY
          # FOD_TENANT: ${{secrets.FOD_TENANT}}
          # FOD_USER: ${{secrets.FOD_USER}}
          # FOD_PASSWORD: ${{secrets.FOD_PAT}}

          ### Optional configuration
          FOD_LOGIN_EXTRA_OPTS: --socket-timeout=60s       # Extra 'fcli fod session login' options
          FOD_RELEASE: ${{ github.event.repository.name }}:${{ github.ref_name }} # FoD release name, default: <org>/<repo>:<branch>
          DO_SETUP: true                                   # Setup FoD application, release & static scan configuration
          # SETUP_ACTION: <URL or file>                    # Customize setup action
          # SETUP_EXTRA_OPTS: --copy-from "${{ github.repository }}:${{ github.event.repository.default_branch }}" # Pass extra options to setup action:
          SETUP_EXTRA_OPTS: --oss --sdlc-status="${{ inputs.sdlc-status }}" --app-type="${{ inputs.app-type }}" --app-criticality="${{ inputs.app-criticality }}"
          SAST_ASSESSMENT_TYPE: ${{ inputs.assessment-type }}
          # Extra 'fcli fod sast-scan start' options
          FOD_SAST_SCAN_EXTRA_OPTS: --oss --entitlement-frequency=${{ inputs.entitlement-frequency }} --entitlement-id=${{ vars.FOD_ENTITLEMENT }} 
          DO_SCA_SCAN: true
          # PACKAGE_EXTRA_OPTS: -oss                       # Extra 'scancentral package' options
          DO_WAIT: true                                    # Wait for successful scan completion (implied if post-scan actions enabled)
          DO_POLICY_CHECK: true                            # Fail pipeline if security policy outcome is FAIL
          # POLICY_CHECK_ACTION: <URL or file>             # Customize security policy checks
          # POLICY_CHECK_EXTRA_OPTS: --on-unsigned=ignore  # Pass extra options to policy check action
          # DO_JOB_SUMMARY: true                           # Generate workflow job summary
          # JOB_SUMMARY_ACTION: <URL or file>              # Customize job summary
          # JOB_SUMMARY_EXTRA_OPTS: --on-unsigned=ignore   # Pass extra options to job summary action
          DO_PR_COMMENT: true                              # Generate PR comments, only used on pull_request triggers
          # PR_COMMENT_ACTION: <URL or file>               # Customize PR comments
          # PR_COMMENT_EXTRA_OPTS: --on-unsigned=ignore    # Pass extra options to PR comment action
          # DO_EXPORT: true                                # Export vulnerability data to GitHub code scanning dashboard
          # EXPORT_ACTION: <URL or file>                   # Customize export action
          # EXPORT_EXTRA_OPTS: --on-unsigned=ignore        # Pass extra options to export action
          # TOOL_DEFINITIONS: <URL>                        # URL from where to retrieve Fortify tool definitions
