name: Fortify AST Workflow For Python with Poetry
description: Fortify AST Workflow For Python with Poetry
on:
  workflow_call:
    inputs:
      runner-version:
        required: false
        type: string
        default: ubuntu-latest
      checkout-paths:
        required: false
        type: string
        default: ''
      python-version:
        required: false
        default: "3.13"
        type: string
      release-name:
        required: True
        type: string    
      sdlc-status:
        required: false
        type: string
        default: "Development"
      application-type:
        required: false
        type: string
        default: "Web"
      application-criticality:
        required: false
        type: string
        default: "Medium"
      entitlement-frequency:
        required: false
        type: string
        default: "Subscription"
      package-extra-opts:
        required: false
        type: string
        default: ""
jobs:
  fortify:
    runs-on: ${{ inputs.runner-version }}
    steps:
      - name: Check out Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.checkout-paths }}
          sparse-checkout-cone-mode: false
      # Setup Poetry
      - name: Setup Python With Poetry ${{ inputs.python-version }}
        uses: cmhmr/workflows-library/.github/actions/setup-python@main
        with:
          python-version: ${{ inputs.python-version }}
      # Run Fortify Scan
      - name: Run Core Application Security SAST/SCA Scans
        uses: cmhmr/workflows-library/.github/actions/setup-fod@main
        with:
          fod-url: ${{ vars.FOD_URL }}
          release-name: ${{ inputs.release-name }}
          sdlc-status: ${{ inputs.sdlc-status }}
          application-type: ${{ inputs.application-type }}
          application-criticality: ${{ inputs.application-criticality }}
          entitlement-frequency: ${{ inputs.entitlement-frequency }}
          entitlement-id: ${{ vars.FOD_ENTITLEMENT }}
          package-extra-opts: ${{ inputs.package-extra-opts }}
        env:
          FOD_CLIENT_ID: ${{ secrets.FOD_CLIENT_ID }}
          FOD_CLIENT_SECRET: ${{ secrets.FOD_CLIENT_SECRET }}
