name: Fortify AST Workflow with Drupal for PHP Project Based
on:
  workflow_call:
    inputs:
      release-name:
        required: True
        type: string
      php-version:
        required: false
        default: "8.3"
        type: string
      sdlc-status:
        description: Release SDLC Status
        required: false
        default: "Development"
        type: string
      application-type:
        description: Application Type
        required: false
        default: "Web_Thick_Client"
        type: string
      application-criticality:
        description: Application Criticality Level
        required: false
        default: "Medium"
        type: string
jobs:
  fortify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v6
      # Setup Poetry
      - name: Setup Drupal for PHP ${{ inputs.php-version }}
        uses: cmhmr/workflows-library/.github/actions/setup-drupal@main
        with:
          php-version: ${{ inputs.php-version }}
      # Run Fortify Scan
      - name: Run Core Application Security SAST/SCA Scans
        uses: cmhmr/workflows-library/.github/actions/setup-fod@main
        with:
          release-name: ${{ inputs.release-name }}
          sdlc-status: ${{ inputs.sdlc-status }}
          application-type: ${{ inputs.application-type }}
          application-criticality: ${{ inputs.application-criticality }}
        env:
          FOD_URL: ${{ vars.FOD_URL }}
          FOD_CLIENT_ID: ${{ secrets.FOD_CLIENT_ID }}
          FOD_CLIENT_SECRET: ${{ secrets.FOD_CLIENT_SECRET }}
          FOD_SAST_SCAN_EXTRA_OPTS: --oss --entitlement-frequency="Subscription" --entitlement-id=${{ vars.FOD_ENTITLEMENT }}